FROM apache/airflow:1.10.12

USER root
RUN apt-get update \
  && apt-get install -y --no-install-recommends \
         build-essential curl vim \
  && apt-get autoremove -yqq --purge \
  && apt-get clean \
  && rm -rf /var/lib/apt/lists/*

USER airflow
# RUN pip install --no-cache-dir --user <what-to-do>

ARG AIRFLOW_HOME=/root/airflow
ENV AIRFLOW_HOME=${AIRFLOW_HOME}

WORKDIR ${AIRFLOW_HOME}

COPY . ./

ENTRYPOINT ["entrypoint.sh"]
CMD ["local"]
